/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nom.songsmin.learnjava.concurrentdemo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void should_get_result() {
        int want = App.sum();
        int got = App.getResult();
        assertEquals(want, got);
    }
}
